#Example of config for multiple DCs/Environments:
#---
#dcs:
#  -
#    name: <name of the datacentre>
#    url: <url of sensu-api>
#    port: <sensu-api port>
#    uchiwa: http://url.to.uchiwa:port
#  -
#    name: local
#    url: local
#    port: 4567
#    user: username
#    password: password
#    uchiwa: http://localhost:3000
#
#app:
#  refresh: 60
#  bg_color: #333333
---
dcs:
  -
    name: dev
    url: localhost
    port: 4567
    uchiwa: http://localhost:3000
  -
    name: qa
    url: localhost
    port: 4568
    uchiwa: http://localhost:3001
  -
    name: stage
    url: localhost
    port: 4569
    uchiwa: http://localhost:3002

app:
  refresh: 60

